### ISSUE TITLE
FreeSound functionality no longer working?

### ISSUE THREAD

**Issue by emmawinston** [gibber-cc/gibber#42]
Hi, 

Am I correct in thinking FreeSound functionality is no longer working in Gibber? If I try to run the tutorial example I get the error 'TypeError: Cannot read property 'protocol' of undefined'. 

I found [this discussion post](http://lurk.org/groups/gibber/messages/topic/295PA35DjqNYlvibTAzo5i) from 2015 but the error in question appears to be different. Has the API just been inaccessible by Gibber since then? I'm a bit late to the party I see. ;) 

Thanks for your work on this, it's an amazing bit of software and I'm sad I didn't get into it when it had more active users!

**Comment by charlieroberts** [comment]
Hmmm... I actually had fixed this since 2015, but now something appears to be broken again... I will look into it.

There's slightly more chatter on the gibber channel in the toplap slack, although even that has been sparse as of late... but I have a new version coming along nicely, so maybe that will pick things up.

**Comment by charlieroberts** [comment]
and thanks for letting me know about this!

**Comment by emmawinston** [comment]
Thanks so much for taking a look, I am attempting a bit of a behemoth of a project with gibber and it would be ace to be able to include some found-sound type stuff, but we'll see. I like a challenge. Delighted to hear there's a new version on the way.

I didn't know there was still a toplap slack and can't seem to find the URL to join - the website says they've moved on to lurk, but lurk also appears to be dead, so I thought maybe there just wasn't anything...

**Comment by charlieroberts** [comment]
Sorry, I should have said rocket chat... the chat moved off of Slack a while back, like you said. It seems to be working for me: http://talk.lurk.org

Let me know if I can do anything else to help with your behemoth project! I'm excited to learn more about it; feel free to email me directly.

**Comment by emmawinston** [comment]
Ah thank you! I definitely had an account there at one point but for some reason kept finding the old Lurk newsgroup instead of the rocket chat. Bookmarked it now. 

Will email you later today. Very excited you're still actively maintaining the project - I keep landing on music programming languages that aren't very widely used any more, and I'm so pleased this one's still ticking along, it seems like there's nothing else around quite like it.

**Comment by serlecu** [comment]
Hi,
there is some issue when running the tutorial of FreeSound at:
 
`// here's a more complex query
c = Freesound({`

I found out that collapsing all lines (removing the comments and line-jumps) of the object solves it. 
Should be something to do with those line jumps.

The error printed at the console:
`
unknown: Unexpected token, expected , (4:7)
bundle.js:78478 error trace:
bundle.js:78479 SyntaxError: unknown: Unexpected token, expected , (4:7)
  2 |         'use jsdsp'
  3 |         c = Freesound({ query:'arcade -loop',sort:'downloads', max:10, count:1
> 4 |       }
    |        ^
    at t.J.raise (babel.min.js:7:10099)
    at t.X.unexpected (babel.min.js:5:27476)
    at t.X.expect (babel.min.js:5:27253)
    at te.parseCallExpressionArguments (babel.min.js:6:27165)
    at te.parseSubscripts (babel.min.js:6:26566)
    at te.parseExprSubscripts (babel.min.js:6:25775)
    at te.parseMaybeUnary (babel.min.js:6:25267)
    at te.parseExprOps (babel.min.js:6:23839)
    at te.parseMaybeConditional (babel.min.js:6:23430)
    at te.parseMaybeAssign (babel.min.js:6:22650)
`

I hope to be helpfull. I'm quite a noob on this.
