### ISSUE TITLE
can't install gibber@2.0.0

### ISSUE THREAD

**Issue by rdbartlett** [gibber-cc/gibber#53]
I've been enjoying the playground for a couple of days so now I want to install Gibber 2 and play with it locally. I've hit a block while trying to install:

```
➜  npm i               

> gibber@2.0.0 install /Users/rich/projects/richdecibels.com/gibber
> npx gulp

[gulp] Using file /Users/rich/projects/richdecibels.com/gibber/gulpfile.js
[gulp] Working directory changed to /Users/rich/projects/richdecibels.com/gibber
Task default requires a function that is a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gibber@2.0.0 install: `npx gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gibber@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rich/.npm/_logs/2020-08-29T20_25_05_769Z-debug.log
```

[2020-08-29T20_25_05_769Z-debug.log](https://github.com/gibber-cc/gibber/files/5145963/2020-08-29T20_25_05_769Z-debug.log)

This is using gulp version 3 and node version 14.9. So I tried switching to gulp v4 and got a different error.

```
➜  npm i               

> gibber@2.0.0 install /Users/rich/projects/richdecibels.com/gibber
> npx gulp

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/rich/projects/richdecibels.com/gibber/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/rich/projects/richdecibels.com/gibber/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/rich/projects/richdecibels.com/gibber/gulpfile.js:46:6)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireOrImport (/Users/rich/projects/richdecibels.com/gibber/node_modules/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gibber@2.0.0 install: `npx gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gibber@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rich/.npm/_logs/2020-08-29T20_29_01_518Z-debug.log
```
[2020-08-29T20_29_01_518Z-debug.log](https://github.com/gibber-cc/gibber/files/5145964/2020-08-29T20_29_01_518Z-debug.log)

Any guidance would be much appreciated!

**Comment by rdbartlett** [comment]
I'm still having some trouble installing from this repo.

However I did manage to overcome the gulp v3 error using [this method](https://timonweb.com/javascript/how-to-fix-referenceerror-primordials-is-not-defined-error/), which has allowed me to install the [gibber.audio.lib repo](https://github.com/charlieroberts/gibber.audio.lib).
