### ISSUE TITLE
Error: I am then unable to build (rebuild) the library/editor by calling npm run build

### ISSUE THREAD

**Issue by dbattin** [gibber-cc/gibber#93]
[BABEL] Note: The code generator has deoptimised the styling of /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/gibberish-dsp/dist/gibberish.js as it exceeds the max of 500KB.
Error: Can't walk dependency graph: Cannot find module 'serialize-javascript' from 'node_modules/gibber.audio.lib/js/clock.js'
    required by /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/gibber.audio.lib/js/clock.js
    at /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/esmify/esmify.js:47:19
    at /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/browser-resolve/index.js:265:24
    at /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/resolve/lib/async.js:139:17
    at processDirs (/Users/db/Desktop/GIBBER_NEW/gibber/node_modules/resolve/lib/async.js:290:39)
    at isdir (/Users/db/Desktop/GIBBER_NEW/gibber/node_modules/resolve/lib/async.js:297:32)
    at /Users/db/Desktop/GIBBER_NEW/gibber/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (node:fs:198:21)

Can you help me or fix it? Many Thanks.

**Comment by charlieroberts** [comment]
I can confirm this is a problem when I do a fresh install.

**Comment by dbattin** [comment]
Many thanks for the quick response. Is it a complicated problem? Is it a complicated problem or can you help me?

**Comment by doctorbling** [comment]
@charlieroberts I just made a fork with the aspiration of updating dependencies ; a vague sub-aspiration was to address this issue, by using a later serialize-javascript version say.

However I just noticed that you committed as recently as September and it made me wonder whether there is a workaround? Eg run off the original source files rather than bundle.js ?

(my apologies if I'm being inadvertantly heretical! I'm new to web development)
